### ISSUE TITLE
Start Sensor

### ISSUE THREAD

**Issue by exoji2e** [exoji2e/Erbil#34]
Currently a new sensor seems to become destroyed if scanned by the app :((((

- [x] Check if sensor is started (and don't destory if not started)
- [x] Start sensor.

**Comment by exoji2e** [comment]
Leaving this here so I dont lose it: [reversing nfc](https://www.cs.ru.nl/bachelors-theses/2012/Hans_Harmannij___3028933___Logging_NFC_data_on_a_Google_Nexus_S.pdf). Easiest to just set up a rooted phone and see what data the original app sends to start a sensor.

**Comment by Powersource** [comment]
what, like it gets bricked lol?

**Comment by exoji2e** [comment]
Yup haha.. this is a #mustfix before I release it to Play :P

**Comment by exoji2e** [comment]
Managed to sniff 2 startups with the app [nfcgate](https://github.com/nfcgate/nfcgate). The startup command is the same, and the magic bytes seems to be: `02 A0 07 C2 AD 75 21`. Will implement for my next sensor and try it out. Then I'm starting to feel ready for GPlay.

**Comment by exoji2e** [comment]
fixed in 56e43ac89ef2f194c497e64540548d941731160c!
