### ISSUE TITLE
Data from sensor.

### ISSUE THREAD

**Issue by theanto** [exoji2e/Erbil#36]
Hi, 

I m looking at your code.
where do you get the raw data from the sensor? I was looking at the code NFCReader.kt but I can't understand where you get the 32 samples and in which variable you are downloading them. Can you tell me this passage?

**Comment by exoji2e** [comment]
Sure, the API for the sensor is not so straight forward that I just request the values. What I do is dump the memory from the sensor and then parse it (which took quite some time to develop, by basically looking at a lot of data dumps):

The function readout: https://github.com/exoji2e/Sugartop/blob/master/app/src/main/java/io/exoji2e/sugartop/NFCReader.kt#L43
reads and returns the entire memory of the nfctag. It reads 8 bytes of data from the nfc memory for each `0x20` command, which is in the [ISO-standard for nfc-communication](http://rfidshop.com.hk/datasheet/HF-TP-RW-USB/RR3036_manual_eng.pdf) (see page 30).

You can find the raw data of the last readings you did in the menu "Show Last Reading Raw".

The actual parsing of the memory into the 32 + 16 data points happens in RawParser.kt:
https://github.com/exoji2e/Sugartop/blob/master/app/src/main/java/io/exoji2e/sugartop/RawParser.kt, which is called from DataContainer.

One thing to note is that the sensor does not measure in a reasonable unit like `mmol/L` or `mg/dL`. It reports some values that linearly corresponds to your glucose level. So what I get for each measurement is an int in the interval [500 - 3000], which I then recalculate based on my own measurements. These parameters to transform from the int to your glucose level can be recalibrated by adding manual glucose measurements.

**Comment by theanto** [comment]
Hi, I tried to read a value log directly by doing
  Log.d ("data", resp.contentToString ());
and I get about 41 arrays this way

[126, 113, 64, 19, 3, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[11, -127, 10, 16, -20, 3, -56, 68]
[-100, -128, -13, 3, -56, 68, -100, -128]
[-19, 3, -56, 60, -100, -128, -11, 3]

and so on ...
from what you're telling me, these values represent the 8 bytes.
I saw the "Show Last Reading Raw" that has the values from 0 to 359 (but the real value is until 327).
I read u comment about (History and Recent, but I really don't understand what they mean).

I tried to log some in RawParser too, but when I read from NFC never call RawParser.kt functions. 
Maybe I should look at the "append" function in DataContainer? 
I'm trying to get that data after you've transformed it for use in some analysis

**Comment by exoji2e** [comment]
I see, yeah, the call to `RawParser` is in `DataContainer.append`

`History` and `Recent` are my names of the different measuring buffers the sensor uses.
Each minute the sensor measures and saves it to the circular buffer `Recent`, which holds measurements for the last 16 minutes.
Each 15th minute a measurement is saved to the `History` buffer, which holds 32 measurements spanning the last 8 hours.

If you want to extract the data the easiest way is to either export a csv-file of the raw measurements, or a sql3 db-dump of the entire app database. You can do that by pressing the Share icon in the upper right corner :)

**Comment by theanto** [comment]
I also tried that one, extracting a .csv, but I extract all the db. I need that every time I take a reading I only extract the 8 hour window.

For example I take a reading now (4 pm) and I take the window of the 8 hours before, values from 9am to 4 pm.
If you export your db now, you will get all the values before 4 pm, even those of the past days, for example yesterday. 

After an NFC reading, you parse the data? Where do I find this window-parsed?

**Comment by exoji2e** [comment]
[Here, in Datacontainer](https://github.com/exoji2e/Sugartop/blob/master/app/src/main/java/io/exoji2e/sugartop/DataContainer.kt#L31)

**Comment by theanto** [comment]
Sorry again for the question. I understand your division between history and recent ones.
I still have a doubt, however, I have analyzed the recent ones (which are the last 16 minutes) but I have values in this format:

SensorChunk (value = 897, status = 200, history = false, rest = 15244672)

Obviously value I think it is the value of glucose (even if it does not correspond to the current one) while what would a timestamp be?

In all the detected values (both history and recent) I did not find the current value, did I still miss something?
Same thing in the story, how do you define the timestamp of those values?

Thank you so much for your support!

**Comment by exoji2e** [comment]
Yes, so timestamps are not set by the sensor, but implied from previous measurements, so them I set later in the function (the recent `history_prepared` and `recent_prepared` variables have all the newly found values.) 

However they are in order, so the last one is the most recent measurement, which for `now_recent` means that it was taken somewhere between just now and one minute ago.

The default transformation from `sensor_values` to `glucose_value` (in `mmol/L`) is:

`glucose_value =  0.00567 * sensor_value - 0.04605`

if you want to get `mg/dL` you just multiply with 18.

This calibration can be changed by adding manual values. The code that applies the transformation can be found in [SensorData.kt](https://github.com/exoji2e/Sugartop/blob/master/app/src/main/java/io/exoji2e/sugartop/SensorData.kt)

**Comment by exoji2e** [comment]
This transformation is not perfect, it was just the mean over multiple sensors that I used. It varies quite a lot. Some sensors become really off when you're at a glucose level of `16-20 mmol/L`. Usually the error is less than a unit away from the default calibration when the values are between `2-8 mmol/L` for me. If you get other results it would be super interesting if you could share :)

**Comment by theanto** [comment]
You will certainly be happy to share my results with you and I hope to be able to contribute with this very interesting project.

The idea is precisely to analyze the data with recent techniques. Collect a lot of data from many sensors and make an analysis that also concerns a lifestyle. I'm doing this for my thesis that will cover digital therapies.

Is it possible that I lose data between the now_recent and now_history and the prepared data?

Correctly I see in now_recent (16 elements) and 32 in now_history,
but once I read the preparations, in history I see it empty (I don't understand why) and the recent ones are only 3 elements.

So the value must still be multiplied then? For example, working with mg / dLf
glucose_value = (0.00567 * sensor_value - 0.04605) * 18 to the value in the "value" object?

**Comment by exoji2e** [comment]
Yes, the `history_prepared` variable only contains values not yet saved to the database.

I think you options are:
- set the timestamps yourself (similar to what is done in the prepare function)
- after the values are inserted into the database you can do a query to the database via [DataContainer.get](https://github.com/exoji2e/Sugartop/blob/master/app/src/main/java/io/exoji2e/sugartop/DataContainer.kt#L123). Note that this is a database function, so it is not allowed to be called from the UI-thread. 

The reason the values are removed between `now_history` and `history_prepared` is because I don't want to save duplicates.

**Comment by exoji2e** [comment]
Closing for now, reopen if need more help/have results to share! :)
