### ISSUE TITLE
Couldn't connect to sensor

### ISSUE THREAD

**Issue by yhesham** [exoji2e/Erbil#37]
Hi first of all thank you for this wonderful  project I have a small issue when I try to scan my libra  2 sensor always give me this error please help me if you can thanks you

**Comment by exoji2e** [comment]
Hi sorry, missed this. The app only works for v1 sensors. I have a v3 now, which has another protocol over bluetooth instead of nfc, so I don't plan to work on this anymore.

**Comment by youssefhesham2** [comment]
Hi thanks for your response I am so appreciate your answer I have another question why always the glucose reading data always not accurate with Libra app can you help me on this thank you,

**Comment by exoji2e** [comment]
I think there are a few reasons:

1. The sensor is not measuring the glucose in the blood, but rather something that is correlated with it.
2. On v1 sensors there was a large discrepency between how off they were the real value. Typically they would show 1-2 units above or below the actual value for me, but be consistently a few units off. Not sure if the v2 had the same problems, but I experience that the v3 is a lot better in this regard.
3. The libre app for v1 used to predict forward in time a lot. I wrote a blog post about that: https://exoji2e.github.io/2019/03/12/glucose-errors.html when it showed 17 going up when my real value was about 8 mmol/L. I think this has improved as well for the v3, not sure about the state regarding this for the v2.

**Comment by youssefhesham2** [comment]
This is a great blog thank you for that. According to my information the Freestyle Libra app predicts the next 10 or 15 minutes of your reading, so the freestyle value will be more accurate with a manual test of blood sugar after 10 or 15 minutes of NFC reading, so I think that The freestyle app is correct, but my question here is there any algorithm to make our application's reading match the freestyle application's reading?
